#
# CircleCI configuration for <%= name %>
#

version: 2
jobs:
  build:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm i --no-progress
      - save_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
      - run: xvfb-run -a npm run test -- --code-coverage --watch false --browsers ChromeNoSandbox
      - run: xvfb-run -a npm run e2e
      - run: npm run coverage
