#
# CircleCI configuration for <%= name %>
#

version: 2

jobs:
  setup:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
      - run: <% if (packageManager === 'npm') { %>npm i --no-progress<% } else { %>yarn --silent<% } %>
      - save_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

  test:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
      - run: <% if (packageManager === 'npm') { %>npm run<% } else { %>yarn<% } %> lint
      - run: <% if (packageManager === 'npm') { %>npm run<% } else { %>yarn<% } %> test<% if (packageManager === 'npm') { %> --<% } %> --configuration ci
      - run: <% if (packageManager === 'npm') { %>npm run<% } else { %>yarn<% } %> e2e
      - run: <% if (packageManager === 'npm') { %>npm run<% } else { %>yarn<% } %> coverage

workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
