#
# CircleCI configuration for <%= name %>
#

version: 2

jobs:
  setup:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm i --no-progress
      - save_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

  test:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/<%= name %>-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run lint
      - run: xvfb-run -a npm run test:ci
      - run: xvfb-run -a npm run e2e
      - run: npm run coverage

workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
