#
# Gitlab configuration for <%= name %>
#

# Stages
stages:
  - setup
  - test

#
# Setup Stage
#

# Setup project
setup:
  stage: setup
  image: circleci/node:8.11.2-browsers
  artifacts:
    name: "node_modules_${CI_COMMIT_REF_SLUG}"
    expire_in: 1d
    paths:
      - node_modules
  script:
    - npm i --no-progress

#
# Test Stage
#

# Test Unit
test_unit:
  stage: test
  image: circleci/node:8.11.2-browsers
  script:
    - npm run lint
    - npm run test -- --code-coverage --watch false --browsers ChromeNoSandbox

# Test Integration
test_integration:
  stage: test
  image: circleci/node:8.11.2-browsers
  script:
    - npm run e2e


