#
# Gitlab configuration for <%= name %>
#

# Stages
stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_NAME}
  untracked: true
  paths:
    - node_modules

#
# Setup Stage
#

# Setup project
setup:
  stage: setup
  image: circleci/node:8.11.2-browsers
  script:
    - npm i --no-progress

#
# Test Stage
#

# Test Unit
test_unit:
  stage: test
  image: circleci/node:8.11.2-browsers
  before_script:
    - npm i --no-progress
  script:
    - npm run lint
    - npm run test:ci

# Test Integration
test_integration:
  stage: test
  image: circleci/node:8.11.2-browsers
  before_script:
    - npm i --no-progress
  script:
    - npm run e2e


