#
# Gitlab configuration for <%= name %>
#

# Stages
stages:
  - setup
  - test

#
# Setup Stage
#

# Setup project
setup:
  stage: setup
  image: circleci/node:8.11.2-browsers
  artifacts:
    expire_in: 1d
    name: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
  script:
    - <% if (packageManager === 'npm') { %>npm i --no-progress<% } else { %>yarn --silent<% } %>


#
# Test Stage
#

# Test Unit
test_unit:
  stage: test
  image: circleci/node:8.11.2-browsers
  script:
    - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> lint
    - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> test <% if (packageManager === 'npm') { %> -- <% } %>--configuration ci



# Test Integration
test_integration:
  stage: test
  image: circleci/node:8.11.2-browsers
  script:
    - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> e2e


