#
# TravisCI configuration for <%= name %>
#

dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

cache:
  <% if (packageManager === 'yarn') { %>yarn: true<% } %>
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - <% if (packageManager === 'npm') { %>npm i --no-progress<% } else { %>yarn --silent<% } %>

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> lint
  - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> test <% if (packageManager === 'npm') { %> -- <% } %>--configuration ci
  - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> e2e
  - <% if (packageManager === 'npm') { %>npm run<% } else { %> yarn<% } %> coverage
