#
# CircleCI configuration for soon schematics
#

version: 2
jobs:
  build:
    working_directory: ~/schematics
    docker:
      - image: mhart/alpine-node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn --silent
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn test
